LowProFool, imperceptible attack on tabular data
Trusted-AI/adversarial-robustness-toolbox pull request #1063
Opened 2021-04-23 20:46 UTC by marcinz99

# Description

New evasion attack is added - LowProFool, imperceptible attack on tabular data.
>`LowProFool` attack transforms the provided real-valued tabular data into adversaries of the specified target classes. The generated adversaries have to be as close as possible to the original samples in terms of the weighted Lp-norm, where the weights determine each feature's importance.
>
>| Paper link: https://arxiv.org/abs/1911.03274

PR includes:
* attack's implementation,
* unit tests,
* notebook presenting usage of the new feature.

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [x] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [x] Tests employing diffentent underlying classifiers and datasets.

**Test Configuration**:
- OS - Windows 10
- Python version - 3.7.10
- ART version or commit number - 1.6.1
- PyTorch version - 1.3.1

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-04-24 22:44 UTC, beat-buesser commented
Hi @marcinz99 Thank you very much for you pull request, we'll start reviewing it as soon as possible.

2021-04-26 21:48 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +    unittest.main()
```suggestion
```

2021-04-26 21:49 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +        print()
Please replace `print` with `logger.info`.

2021-04-26 21:50 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +        print()
Please replace `print` with `logger.info`.

2021-04-26 21:50 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +        print()
Please replace `print` with `logger.info`.

2021-04-26 21:50 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +        print()
Please replace `print` with `logger.info`.

2021-04-26 21:52 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +        return self.model.predict_proba(x)
Please replace with `art.estimators.classification.SklearnLogisticRegression` updated with branch `development_issue_1064`.

2021-04-26 21:53 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +class TestLowProFool(unittest.TestCase):
Please convert to pytest format similar to the other tests in `tests/attacks/evasion`.

2021-04-26 21:54 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +from typing import Any, Callable, Dict, List, Optional, Tuple, Union, Type, TYPE_CHECKING
```suggestion
import logging
from typing import Any, Callable, Dict, List, Optional, Tuple, Union, Type, TYPE_CHECKING

import numpy as np
from scipy.stats import pearsonr
from tqdm.auto import trange

from art.attacks.attack import EvasionAttack
from art.estimators.estimator import LossGradientsMixin
from art.estimators.estimator import BaseEstimator
from art.estimators.classification.classifier import ClassifierMixin
```

2021-04-26 21:56 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +    attack_params = EvasionAttack.attack_params + [
```suggestion
    """

    attack_params = EvasionAttack.attack_params + [
```

2021-04-26 21:56 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +            verbose: Optional[bool] = False
```suggestion
        self,
        classifier: "CLASSIFIER_CLASS_LOSS_GRADIENTS_TYPE",
        n_steps: Optional[Optional[int]] = 100,
        threshold: Optional[Optional[Union[float, None]]] = 0.5,
        lambd: Optional[float] = 1.5,
        eta: Optional[float] = 0.2,
        eta_decay: Optional[float] = 0.98,
        eta_min: Optional[float] = 1e-7,
        p: Optional[Union[int, float, str]] = 2,
        importance: Optional[Union[Callable, str, np.ndarray]] = "pearson",
        verbose: Optional[bool] = False,
```

2021-04-26 22:00 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +            y_probas: np.ndarray,
The argument `y_probas` seems unused. Is this ok or can we remove `y_probas`?

2021-04-26 22:00 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +            (targets).astype(np.float32)
```suggestion
            targets.astype(np.float32)
```

2021-04-26 22:01 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +        for i in trange(self.n_steps, desc="LowProFool", disable=not(self.verbose)):
```suggestion
        for i in trange(self.n_steps, desc="LowProFool", disable=not self.verbose):
```

2021-04-26 22:03 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +        if not (importance_array is None):
```suggestion
        if importance_array is not None:
```

2021-04-26 22:07 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +            p: Optional[Union[int, float, str]] = 2,
Please replace `p` with `norm` similar to the other evasion attacks.

2021-04-26 22:08 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +        ).reshape(-1, 1)
Could this method or parts of it be replaced with the existing `sklearn.metrics.log_loss`?

2021-04-26 22:11 UTC, beat-buesser commented on art/attacks/evasion/lowprofool.py
> +    def __classification_loss_gradient(
This method is just one line and used only once. Please inline the call to `self.estimator.loss_gradient` and replace the call to `__classification_loss_gradient`.

2021-04-26 22:18 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +from art.estimators.classification.scikitlearn import ScikitlearnSVC
```suggestion
import logging
import unittest

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.autograd import Variable
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from scipy.stats import pearsonr

from art.attacks.evasion import LowProFool
from art.estimators.classification import PyTorchClassifier
from art.estimators.estimator import LossGradientsMixin
from art.estimators.estimator import BaseEstimator
from art.estimators.classification.classifier import ClassifierMixin
from art.estimators.classification.scikitlearn import ScikitlearnSVC
```

2021-04-26 22:21 UTC, beat-buesser commented on tests/attacks/evasion/test_lowprofool.py
> +                    param.data -= learning_rate * param.grad
```suggestion
    optimizer = optim.SGD(nn_model.parameters(), lr=0.001, momentum=0.9)
    
    for _ in range(epoches):
        y_pred = nn_model.forward(X)
        loss = self.loss_fn(y_pred, y)
        nn_model.zero_grad()
        loss.backward()
        
        optimizer.step()
```

2021-04-26 22:40 UTC, beat-buesser requested changes
Hi @marcinz99 Thank you very much for implementing the `LowProFool` evasion attack, the first attack specifically for tabular data! Your code is well organised and follows the patterns of ART very well.

I have made a few change request inline above. We should update this PR with the upcoming changes to ART 1.6.2 on branch `development_issue_1064` to resolve #1064 opened by you recently.

Following the updates for #1064, could you please remove cell 18 of the notebook and the markdown comment cell before cell 18?

Could you also please take a look at the failing style check in the CI runs and address the warnings raised by `mypy`, `pylint` and `pycodestyle`? Please run first Black formatter `black==20.8b1` on `art/` and `tests/` with command `black --line-length 120 path` which should address some of the warnings.

2021-04-27 19:37 UTC, marcinz99 commented
Hi @beat-buesser Thanks for the comprehensive feedback. We will try to go through your comments and remarks shortly, but I have to inform you that as for the time being we have lots of work related to the current university courses. Therefore we will apply the necessary corrections to the code no sooner than the next week or so.

Regarding the cell 18 of the notebook (custom scikit-learn logistic regression wrapper), we thought that it would be nice to 
actually show the user how to create a custom wrapper, just in case they couldn't use any built-in one. Especially as we had priorly created one ourselves and it turned out to be pretty concise. Do you find it reasonable to leave it there to serve such a purpose then?

2021-04-29 23:26 UTC, beat-buesser commented
> Regarding the cell 18 of the notebook (custom scikit-learn logistic regression wrapper), we thought that it would be nice to
> actually show the user how to create a custom wrapper, just in case they couldn't use any built-in one. Especially as we had priorly created one ourselves and it turned out to be pretty concise. Do you find it reasonable to leave it there to serve such a purpose then?

Hi @marcinz99 I think it is better to remove it, because it us replicating an existing estimator of ART and because the focus of the notebook should be on `LowProFool`.

2021-04-29 23:33 UTC, beat-buesser commented
@marcinz99 This pull request contains a new tool, therefore you can add the name of your university to the [AUTHORS](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/AUTHORS) file if you like.

2021-05-07 22:38 UTC, beat-buesser approved these changes
Hi @marcinz99, @jupiterb, @czyjtu, @kocimski, and @ArcziPT

Congratulations for your first contribution to ART and thank you very much for implementing the `LowProFool` evasion attack on tabular data and addressing all review comments! Great work!

2021-05-07 22:38 UTC, merged