Stateful Detection of Black-Box Adversarial Attacks
Trusted-AI/adversarial-robustness-toolbox pull request #1420
Opened 2021-11-21 18:38 UTC by twrdyyy

# Description
Close #1373 
@beat-buesser 
As proposed in https://arxiv.org/pdf/1907.05587.pdf paper.
This PR introduces new defence agains attacks on black-box classifier.  Example notebook of usage is provided inside the PR in **notebooks/defence_black_box_pytorch_example.ipynb**

New classes introduced:
1. **BlackBoxDetector** - performs scan on given query
 -> art.defences.detector.evasion.black_box.detector 
2. **MemoryQueue** - Used by detector, saves encoded query, has fixed length and is implemented fully in numpy library
 -> art.defences.detector.evasion.black_box.memory_queue
3. **NearestNeighborsWrapper** - Wrapper for sklearn Nearest Neighbor class to be properly used in ART
 -> art.defences.detector.evasion.black_box.knn_wrapper

There are also new loss function named *contrastive_loss*, implemented purely in numpy, in tensorflow and in pytorch.

## Type of change

Please check all relevant options.

- [X] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [X] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

**I do not know if we need some unit tests for this implementation, if we do please comment out so I will add them!**

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-11-21 18:48 UTC, twrdyyy commented
@beat-buesser The DCO CI wanted me to sign-off the commits

2021-11-21 18:51 UTC, twrdyyy commented
Please review the changes and guide me what to do to properly integrate it to 1.9.0 branch 😄

2021-11-21 22:30 UTC, beat-buesser commented
Thank you very much for your pull request, we will review it as soon as possible.

2021-11-25 21:05 UTC, beat-buesser commented
Hi @twrdyyy It looks like you have accidentally signed commits of other authors. Could you please update your branch to only have your own signed commits on top of `dev_1.9.0`?

2021-11-26 10:03 UTC, twrdyyy commented
Hey, Yes I will correct this, how about the code?

2021-11-28 13:28 UTC, twrdyyy commented
@beat-buesser I've rebased this branch to dev_1.9.0 version and have updated all the commits

2021-11-29 13:23 UTC, beat-buesser commented
Before we take a closer look at the code, could you please update the notebook to reproduce the data point for Boundary Attack in Table 1? Please add as many comments to the notebook as possible to explain each step.

2021-11-29 13:31 UTC, twrdyyy commented
I will update the notebook today, but what exactly do you mean by Table 1? And by adding Boundary Attack you mean to include this after the HopSkipJump attack sure? @beat-buesser

2021-11-29 22:35 UTC, beat-buesser commented
With Table 1 I meant the results of [Chen et al.](https://arxiv.org/pdf/1907.05587.pdf ) presented in their Table 1 and discussed in their section 4.2. I think it would be good to see if the if this pull request can achieve a comparable number of detections (e.g. their 288).

2021-12-07 02:49 UTC, twrdyyy commented
@beat-buesser I've added Boundary attack to notebook and have done some cleanup. Both encoder and classifier models were added to /notebooks/models as weights to be loaded inside example notebook. If you would like to see the comparison with table 1, I did some tests. For Boundary attack for over 1000 attack on MNIST data:
* num of queries - 54752
* attacks detected - 1000
* detection success rate - 100%

For threshold = 0.003, K-neighbours = 20 and max_queue size = 100

I did not include this in notebook as it takes some time to calculate.

2021-12-07 23:47 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/contrastive_loss.py
> +| Paper link: https://arxiv.org/abs/1907.05587
```suggestion
Contrastive loss functions

| Paper link: https://arxiv.org/abs/1907.05587
```

2021-12-07 23:48 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/contrastive_loss.py
> +from math import sqrt
```suggestion
from math import sqrt

import numpy as np
import tensorflow as tf
import torch
```

2021-12-07 23:49 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/contrastive_loss.py
> +    Contrastive loss function implemented for numpy as proposed in paper:
Change format to ART docstring style and add params and returns.

2021-12-07 23:49 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/contrastive_loss.py
> +    Contrastive loss function implemented for pytorch as proposed in paper:
Change format to ART docstring style and add params and returns.

2021-12-07 23:49 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/contrastive_loss.py
> +    Contrastive loss function implemented for tensorflow as proposed in paper:
Change format to ART docstring style and add params and returns.

2021-12-07 23:50 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/contrastive_loss.py
> +import tensorflow as tf
Move imports of TensorFlow and PyTorch into the functions requiring them to make the module framework independent. Use `if TYPE_CHECKING:` for typing.

2021-12-07 23:51 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/detector.py
> +| Paper link: https://arxiv.org/abs/1907.05587
```suggestion
Stateful detection on Black-Box  Adversarial Attacks.

| Paper link: https://arxiv.org/abs/1907.05587
```

2021-12-07 23:51 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/detector.py
> +    | Paper link: https://arxiv.org/abs/1907.05587
```suggestion
    Stateful detection on Black-Box Adversarial Attacks.
    
    | Paper link: https://arxiv.org/abs/1907.05587
```

2021-12-07 23:52 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/detector.py
> +        | Paper link: https://arxiv.org/abs/1907.05587
```suggestion
        Stateful detection on Black-Box Adversarial Attacks.
        
        | Paper link: https://arxiv.org/abs/1907.05587
```

2021-12-07 23:54 UTC, beat-buesser commented on art/estimators/encoding/pytorch.py
> +# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2020
```suggestion
# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2021
```

2021-12-07 23:54 UTC, beat-buesser commented on art/estimators/encoding/pytorch.py
> +    def __init__(
Apply Black formatter with line length 120.

2021-12-07 23:58 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/memory_queue.py
> +class MemoryQueue:
Could you please add an abstract base class for `Memory` to enable different implementations?

2021-12-07 23:58 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/memory_queue.py
> +        Extends queue with new elements
Please add params to docstring.

2021-12-07 23:59 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/memory_queue.py
> +        :param max_size: Maximum number of elements stored in memory queue
Add `element_shape`.

2021-12-07 23:59 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/knn_wrapper.py
> +        memory_queue: MemoryQueue,
Change `MemoryQueue` to new abstract base class.

2021-12-08 00:01 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/knn_wrapper.py
> +from sklearn.neighbors import NearestNeighbors
Move the import of sklearn inside of the class/methods requiring it to make the module framework-independent.

2021-12-08 00:05 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/knn_wrapper.py
> +        :param query: Query for which we calculate mean distance
Add params.

2021-12-08 00:05 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/knn_wrapper.py
> +    def update_memory(self):
Add docstring.

2021-12-08 00:12 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/knn_wrapper.py
> +class NearestNeighborsWrapper:
To enable different nearest neighbor searches:
- Move module to `art.estimators.neighbors.scikit.learn.py`
- Create abstract mixin-class `NeighborMixin` defining abstract method `predict` to replace the current `__call__` and `fit to replace the current `update_memory`.
- Update method names in this class

2021-12-08 00:13 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/knn_wrapper.py
> +class NearestNeighborsWrapper:
```suggestion
class ScikitlearnNearestNeighbors:
```

2021-12-08 00:14 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/knn_wrapper.py
> +This module implements wrapper for sklearn knn algorithm.
```suggestion
This module implements estimator for scikit-learn NearestNeighbors.
```

2021-12-08 00:16 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/detector.py
> +class BlackBoxDetector(NeuralNetworkMixin, BaseEstimator, ABC):
```suggestion
class StatefulBlackBoxDetector(BaseEstimator):
```

2021-12-08 00:17 UTC, beat-buesser commented on art/defences/detector/evasion/black_box/__init__.py
> +)
```suggestion
```

2021-12-08 00:23 UTC, beat-buesser requested changes
Hi @twrdyyy 
Please take a look at my suggestions above, some minor changes and relocating classes for future extensions.

After these changes, please create a test module for each new module in `tests` using **pytest**.

Please also take a look at the log of the Style Check CI run and fix their alerts if needed.

The notebook look much better now, maybe see if you can write a few sentences around the most important cells to describe what is happening and add links to the paper, etc. Shortly before merging we can move the models to our large file storage for the notebook support data.

2021-12-16 14:51 UTC, twrdyyy commented
@beat-buesser I will make those changes during the weekend, because I had to finish my paper during last two weeks. Thanks for review! I will make everything as you said.

2022-01-06 14:40 UTC, twrdyyy commented
@beat-buesser I am sorry for being inactive here, but I had some major problems with paper and finishing the thesis I see that ART is updated to 1.9 so I will do the following changes to 1.10

2022-01-06 15:44 UTC, beat-buesser commented
Hi @twrdyyy Sounds good, let me know when I can help.

2022-03-17 00:27 UTC, beat-buesser commented
Please reopen pull request if work continues.

2022-03-17 00:27 UTC, closed without merging