Implement GRAPHITE Attack
Trusted-AI/adversarial-robustness-toolbox pull request #1751
Opened 2022-06-28 17:08 UTC by ryan-feng

# Description

Add GRAPHITE attack (https://arxiv.org/pdf/2002.07088.pdf, https://github.com/ryan-feng/GRAPHITE)

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [X] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [X] Tested with notebooks
- [X] Independently tested for correctness
- [ ] Test cases added, did not know how to run outside of the PR

**Test Configuration**:
- OS - Ubuntu
- Python 3.8
- ART version or commit number: f073851ae325a3ac50d9f53e54f2cf14f9b95781
- Torch version 1.7

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-14 16:40 UTC, keykholt reviewed
Made some minor comments about type hinting.

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2019
Change the year to 2022

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        mask: Optional[np.ndarray],
I think if you are using optional here, you should explicitly set the default value to None. You might also want to move it to the end of the arg list. This also occurs on lines 311, 373, 502, 547, 593, 656, 731,

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        pts: Optional[np.ndarray],
Should assign it with a default value of None and move to the end of the arg list.

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        pts: Optional[np.ndarray],
Should assign it with a default value of None and move to the end of the arg list.

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2019
Changed to 2022

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2019
change to 2022

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    pts: Optional[np.ndarray],
Should assign it with a default value of None and move to the end of the arg list.

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    pts: np.ndarray,
Why is this not marked as optional? On line 355, it gets passed pts, which could be optional.

2022-07-14 16:40 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    pts: np.ndarray,
I think on line 355, this arg could be optional, but it is not marked as optional here.

2022-07-14 16:40 UTC, keykholt commented on tests/attacks/test_graphite.py
> +# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2018
Change to 2022

2022-07-14 18:09 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2019
```suggestion
# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2022
```

2022-07-14 18:16 UTC, keykholt requested changes

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2019
```suggestion
# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2022
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        mask: Optional[np.ndarray],
```suggestion
        mask: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
Move to end of arg list as well

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
Move to end of arg list

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
Move to end of arg list also

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
Move to end of arg list

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
Move to end of arg list

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
Move to end of arg list

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        pts: Optional[np.ndarray],
Move to end of arg list

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        pts: Optional[np.ndarray],
Move to end of arg list

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        pts: Optional[np.ndarray],
```suggestion
        pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        pts: Optional[np.ndarray],
Move to end of arg list also

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2019
```suggestion
# Copyright (C) The Adversarial Robustness Toolbox (ART) Authors 2022
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    pts: Optional[np.ndarray],
```suggestion
    pts: Optional[np.ndarray] = None,
```

2022-07-14 18:16 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    pts: Optional[np.ndarray],
This is tagged as optional, but then passed to other functions that mark it as required?

2022-07-19 23:22 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +            if estimator.channels_first:
I think you might want to use a different type or check to make sure that channels_first is an attribute

2022-07-21 16:04 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    assert isinstance(x_adv_tmp, "torch.Tensor")
Probably wouldn't have an assert here. Also, I think the string --> tensor will only work if type checking is enabled. Also, can't get_perspective_transform also return a numpy type>

If you do want an assert, replace it with an `if isinstance: raise SpecificError(errormsg)` form

2022-07-21 16:08 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +            assert isinstance(final_avg_grad, "torch.Tensor")
Can't use a string here as it only turns into a tensor type if type checking is being done I think. Also, if you want to type check, you should use an `if  not isinstance(): raise SpecificError(errormsg)`.

2022-07-21 16:08 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +            assert isinstance(transform_robustness, float)
if you want to type check, you should use an if not isinstance(): raise SpecificError(errormsg).

2022-07-21 16:10 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        assert isinstance(y, np.ndarray)
if you want to type check, you should use an if not isinstance(): raise SpecificError(errormsg).

2022-07-21 16:10 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        assert isinstance(mask, np.ndarray)
if you want to type check, you should use an if not isinstance(): raise SpecificError(errormsg).

2022-07-22 15:00 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +            mask = np.ones((self.noise_size[1], self.noise_size[0], x.shape[2]))
```suggestion
        if mask is None:
            mask_array = np.ones((self.noise_size[1], self.noise_size[0], x.shape[2]))
        else:
            mask_array = mask
```

2022-07-22 15:02 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        mask = mask / np.max(mask)
Renaming to the new variable name
```suggestion
        mask_array = mask_array / np.max(mask_array)
```

2022-07-26 18:09 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        :param x: An array with one original input to be attacked.
```suggestion

        :param x: An array with one original input to be attacked.
```

2022-07-26 18:09 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        :param x: An array with one original input to be attacked.
```suggestion

        :param x: An array with one original input to be attacked.
```

2022-07-26 18:10 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        :param x: An array with one original input to be attacked.
```suggestion

        :param x: An array with one original input to be attacked.
```

2022-07-26 18:10 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        :param x: An array with one original input to be attacked.
```suggestion

        :param x: An array with one original input to be attacked.
```

2022-07-26 18:10 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        :param x: An array with one original input to be attacked.
```suggestion

        :param x: An array with one original input to be attacked.
```

2022-07-26 18:10 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        :param x: An array with one original input to be attacked.
```suggestion

        :param x: An array with one original input to be attacked.
```

2022-07-26 18:11 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        :param x: Original image.
```suggestion

        :param x: Original image.
```

2022-07-26 18:11 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        :param x: An array with one original input to be attacked.
```suggestion

        :param x: An array with one original input to be attacked.
```

2022-07-26 18:11 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param dist: Distance to object.
```suggestion

    :param dist: Distance to object.
```

2022-07-26 18:11 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param x: Input image.
```suggestion

    :param x: Input image.
```

2022-07-26 18:11 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param x: Input image.
```suggestion

    :param x: Input image.
```

2022-07-26 18:12 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param num_xforms: The number of transforms to sample.
```suggestion

    :param num_xforms: The number of transforms to sample.
```

2022-07-26 18:12 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param x: Input image.
```suggestion

    :param x: Input image.
```

2022-07-26 18:12 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param x: Input image.
```suggestion

    :param x: Input image.
```

2022-07-26 18:12 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param x: Original input image.
```suggestion

    :param x: Original input image.
```

2022-07-26 18:12 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param x: Input image.
```suggestion

    :param x: Input image.
```

2022-07-26 18:12 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param img: Input image.
```suggestion

    :param img: Input image.
```

2022-07-26 18:13 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param img: Input image.
```suggestion

    :param img: Input image.
```

2022-07-26 18:13 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param angle: Angle to rotate.
```suggestion

    :param angle: Angle to rotate.
```

2022-07-26 18:13 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param w: Width of image.
```suggestion

    :param w: Width of image.
```

2022-07-26 18:13 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param estimator: The model.
```suggestion

    :param estimator: The model.
```

2022-07-26 18:14 UTC, keykholt commented on art/attacks/evasion/graphite/utils.py
> +    :param mask: The mask.
```suggestion

    :param mask: The mask.
```

2022-09-06 16:35 UTC, beat-buesser commented
Closing this PR because work continues in #1828

2022-09-06 16:35 UTC, closed without merging