Implement GRAPHITE attack, fixed
Trusted-AI/adversarial-robustness-toolbox pull request #1828
Opened 2022-08-24 20:33 UTC by ryan-feng

# Description

Add GRAPHITE attack (https://arxiv.org/pdf/2002.07088.pdf, https://github.com/ryan-feng/GRAPHITE)

Fixes #1751 

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [X] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [X] Tested with notebooks
- [X] Independently tested for correctness
- [ ] Test cases added, did not know how to run outside of the PR

**Test Configuration**:
- OS - Ubuntu
- Python 3.8
- ART version or commit number: dev_1.12.0
- Torch version 1.7

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-06 16:24 UTC, keykholt requested changes

2022-09-06 16:24 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        :param heatmap_mode: The mode of heatmap in ['Target', 'Random'].
This is a bit vague. I assume this refers to the heatmap generation method. The values can be ['Target', 'Random']. A minor suggestion would be to not make this variable case sensitive.

2022-09-06 16:24 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_blackbox.py
> +        if self.heatmap_mode == "Random":
One place to make case-insensitive if you decide to make a change to the heatmap_mode

2022-09-06 16:24 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +This module implements the white-box version of the GRAPHITE attack `GRAPHITEWhiteboxPyTorch`.
```suggestion
This module implements the white-box PyTorch version of the GRAPHITE attack `GRAPHITEWhiteboxPyTorch`.
```

2022-09-06 16:24 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +    Implementation of the white-box GRAPHITE attack from Feng et al. (2022). This is a physical attack
```suggestion
    Implementation of the white-box PyTorch GRAPHITE attack from Feng et al. (2022). This is a physical attack
```

2022-09-06 16:29 UTC, keykholt commented
Looks good, I think I just want to clarify that this only seems to implement a whitebox attack for pytorch and not other estimator types.

2022-09-06 16:30 UTC, keykholt requested changes

2022-09-06 16:30 UTC, keykholt commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        classifier: "CLASSIFIER_NEURALNETWORK_TYPE",
This seems to only support PyTorchClassifiers based on the inputs to the other methods?

2022-09-07 00:42 UTC, ryan-feng commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +        classifier: "CLASSIFIER_NEURALNETWORK_TYPE",
```suggestion
        classifier: "PyTorchClassifier",
```

2022-09-07 00:43 UTC, ryan-feng commented on art/attacks/evasion/graphite/graphite_whitebox_pytorch.py
> +    from art.utils import CLASSIFIER_NEURALNETWORK_TYPE
```suggestion
    from art.estimators.classification.pytorch import PyTorchClassifier
```

2022-09-08 16:56 UTC, keykholt approved these changes

2022-09-09 09:35 UTC, beat-buesser approved these changes
Hi @ryan-feng Thank you very much for contributing GRAPHITE to ART!

@keykholt Thank you very much for supporting and reviewing this PR!

2022-09-09 09:35 UTC, merged