Adding YOLO examples to ART
Trusted-AI/adversarial-robustness-toolbox pull request #1854
Opened 2022-09-23 11:43 UTC by kieranfraser

Signed-off-by: Kieran Fraser <kieran.fraser@ibm.com>

# Description

Demonstrating YOLO v3 and YOLO v5 support within ART. Addition of "get started" files for each which demonstrates how to instantiate YOLO object detectors with ART, run a PGD attack and visually evaluate the result.

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-14 12:13 UTC, beat-buesser commented on examples/get_started_yolo.py
> +plot_image_with_boxes(img=image_adv[0].transpose(1,2,0).copy(), boxes=preds[1], pred_cls=preds[0], title="Predictions on adversarial image")
Please add empty line at the end of the file.

2022-10-14 12:52 UTC, beat-buesser commented on examples/get_started_yolo.py
> +    class Yolo(torch.nn.Module):
Could you please update the docstrings of `PyTorchYolo` where the model is input to mention that a wrapper is required as shown in this example?

2022-10-14 12:55 UTC, beat-buesser requested changes
Hi Kieran, thank you very much for your first pull request to ART!

I have left a few comments above, what do you think?

Could you also please check the reports of the style checks?

Could you please run the notebook for more iterations, e.g. 1000 with optimizer `pgd` and learning rate of 1?

2022-10-18 10:50 UTC, kieranfraser commented
> Hi @kieranfraser , thank you very much for your first pull request to ART!
> 
> I have left a few comments above, what do you think?
> 
> Could you also please check the reports of the style checks?
> 
> Could you please run the notebook for more iterations, e.g. 1000 with optimizer `pgd` and learning rate of 1?

Thanks @beat-buesser! 

I have included your suggestions in the my latest additions and the style checks are now passing. I also ran the notebook with 1000 iterations, optimizer `pgd` and learning rate 1. Should I commit and push that notebook so those results are visible?

2022-10-19 16:55 UTC, kieranfraser commented
> > Hi @kieranfraser , thank you very much for your first pull request to ART!
> > I have left a few comments above, what do you think?
> > Could you also please check the reports of the style checks?
> > Could you please run the notebook for more iterations, e.g. 1000 with optimizer `pgd` and learning rate of 1?
> 
> Thanks @beat-buesser!
> 
> I have included your suggestions in my latest additions and the style checks are now passing. I also ran the notebook with 1000 iterations, optimizer `pgd` and learning rate 1. Should I commit and push that notebook so those results are visible?

Added notebook with results of run with 1000 iterations.

2022-11-01 22:25 UTC, beat-buesser approved these changes
Hi @kieranfraser Thank you very much and congratulations for your first accepted pull request to ART!

2022-11-01 22:25 UTC, merged