Implement Default Training Loop for `TensorFlowV2Classifier`
Trusted-AI/adversarial-robustness-toolbox pull request #2124
Opened 2023-04-24 22:18 UTC by f4str

# Description

Please include a summary of the change, motivation and which issue is fixed. Any dependencies changes should also be included.

Fixes #2083 

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-05-10 09:25 UTC, beat-buesser commented on art/attacks/evasion/brendel_bethge.py
> +                optimizer=estimator._optimizer,
Should we use the new property:
```suggestion
                optimizer=estimator.optimizer,
```

2023-05-10 09:31 UTC, beat-buesser requested changes
Hi @f4str Thank you very much for implementing a default training step for TensorFlow v2 classifiers! I have added a few suggestions, what do you think?

2023-05-10 09:31 UTC, beat-buesser commented on art/attacks/evasion/brendel_bethge.py
> +                optimizer=estimator._optimizer,
Should we use the new property:
```suggestion
                optimizer=estimator._optimizer,
```

2023-05-10 09:31 UTC, beat-buesser commented on art/attacks/evasion/auto_projected_gradient_descent.py
> +                    optimizer=estimator._optimizer,
Should we use the new property:
```suggestion
                    optimizer=estimator.optimizer,
```

2023-05-10 09:31 UTC, beat-buesser commented on art/attacks/evasion/brendel_bethge.py
> +                optimizer=estimator._optimizer,
Should we use the new property:
```suggestion
                optimizer=estimator.optimizer,
```

2023-05-10 09:31 UTC, beat-buesser commented on art/attacks/evasion/auto_conjugate_gradient.py
> +                    optimizer=estimator._optimizer,
Should we use the new property:
```suggestion
                    optimizer=estimator.optimizer,
```

2023-05-10 18:20 UTC, f4str commented
Hi @beat-buesser thank you for the comments! For consistency, `optimizer` currently uses the private attribute instead of the public since `loss_object` and `train_step` use the private attribute. So all of these should use either the private attribute or public property to stay consistent.

Since ART is shifting from private attributes to public properties, I think it may be worth changing all of these (`optimizer`, `loss_obejct`, and `train_step`) to use the public property, but only for the affected files in this PR alone. Any thoughts on this?

2023-05-29 12:51 UTC, beat-buesser approved these changes

2023-05-29 12:52 UTC, beat-buesser commented
Hi @f4str Thank you very much, the updates look good to me.

2023-05-29 12:52 UTC, merged