Update adversarial_training_FBF.py, adversarial_training_data_augmentation.py, get_started_xgboost.py and mnist_cnn_fgsm.py
Trusted-AI/adversarial-robustness-toolbox pull request #2194
Opened 2023-06-16 16:32 UTC by Foxglove144

# Description

1. In adversarial_training_FBF.py, added correct import statement for PyTorchClassifier.
2. In adversarial_training_data_augmentation.py, disabled TensorFlow eager execution. 
3. In get_started_xgboost.py, added correct eval_metric paramters.
4. In mnist_cnn_fgsm.py, disable TensorFlow eager execution and demonstrate FGSM over multiple epsilon values.

Fixes # (issue)

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-06-26 10:50 UTC, beat-buesser commented on examples/mnist_cnn_fgsm.py
> +    x_test_adv = adv_crafter.generate(x=x_test)
we could make the attack even stronger by attacking the true labels
```suggestion
    x_test_adv = adv_crafter.generate(x=x_test, y=y_test)
```

2023-06-26 10:52 UTC, beat-buesser requested changes
Hi @Foxglove144 Thank you very much for updating all example scripts. I like the extension to the FGSM example on MNIST where I have added a small suggestion to make the attack stronger. What do you think?

2023-06-26 17:50 UTC, Foxglove144 commented
i'm sorry I seem to have accidentally committed your changes without signing off and I messed up trying to revert the file. Can you please tell me how to fix this?

2023-06-27 12:59 UTC, beat-buesser commented
Hi @Foxglove144 I think something went wrong with the last signing-off of commits that signed the commits of dependabot. Could you please move your commits with`git cherry-pick` to a new branch so that I can merge your changes without the double-signed commits?

2023-06-29 19:48 UTC, closed without merging