adding adversarial weight perturbation protocol
Trusted-AI/adversarial-robustness-toolbox pull request #2224
Opened 2023-07-20 00:08 UTC by Zaid-Hameed

# Description

AWP is an important adversarial training approach because it provides better robustness against adversarial attacks and mitigates robust overfitting. AWP has been proposed in paper "Adversarial Weight Perturbation Helps
Robust Generalization".

Paper link: https://proceedings.neurips.cc/paper/2020/file/1ef91c212e30e14bf125e9374262401f-Paper.pdf

It is also a base component of more advanced adversarial training approaches.

Fixes #2164

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [x] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [x] Adversarial weight perturbation based training implementation produces results similar to original implementation
- [x] All functions in implemented code work as expected

**Test Configuration**:
- OS: Red Hat Enterprise Linux 8.7 (Ootpa)
- Python version: 3.9.12
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version: PyTorch 1.13.1+cu117

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-08-03 12:09 UTC, beat-buesser requested changes
Hi @Zaid-Hameed Thank you very much for your pull request! I have added a few minor comments on using properties to avoid pylint warnings. What do you think?

Have you tested your code on GPUs?

2023-08-15 11:42 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        ):  # pylint: enable=W0212
Yes, I checked on internet and found this to be the solution when it is in the forms of a condition.

2023-08-18 11:31 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp.py
> +This module implements adversarial training with AWP protocol.
Done.

2023-08-18 11:31 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +    Class performing adversarial training following AWP protocol.
Done.

2023-08-18 11:31 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +EPS = 1e-8
Addes definition.

2023-08-18 11:32 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        self._apply_wp: bool
Yes, for static type checking by mypy.

2023-08-18 11:32 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        ):  # pylint: enable=W0212
Fixed I according to our discussion.

2023-08-18 11:32 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +            for batch_id in range(nb_batches):  # pylint: disable=W0612
Done.

2023-08-18 11:32 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        self._classifier._model.train(mode=False)  # pylint: disable=W0212
Done.

2023-08-18 11:33 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        if self._classifier._optimizer is None:  # pylint: disable=W0212
Done.

2023-08-18 11:33 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        if self._proxy_classifier._optimizer is None:  # pylint: disable=W0212
Done.

2023-08-18 11:33 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        o_batch = torch.from_numpy(y_preprocessed).to(self._classifier._device)  # pylint: disable=W0212
Done.

2023-08-18 11:33 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        self._classifier._model.train(mode=True)  # pylint: disable=W0212
Done.

2023-08-18 11:34 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        self._classifier._optimizer.zero_grad()  # pylint: disable=W0212
Done.

2023-08-18 11:35 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +            loss = self._classifier._loss(model_outputs_pert[-1], o_batch)  # pylint: disable=W0212
Done.

2023-08-18 11:35 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +            model_outputs_pert = self._classifier._model(i_batch_pert)  # pylint: disable=W0212
Done.

2023-08-18 11:35 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +            loss_clean = self._classifier._loss(model_outputs[-1], o_batch)  # pylint: disable=W0212
Done.

2023-08-18 11:36 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        self._classifier._optimizer.step()  # pylint: disable=W0212
Done.

2023-08-18 11:36 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +            loss = -self._proxy_classifier._loss(model_outputs_pert[-1], y_batch)  # pylint: disable=W0212
Done.

2023-08-18 11:36 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +            loss_clean = self._proxy_classifier._loss(model_outputs[-1], y_batch)  # pylint: disable=W0212
Done.

2023-08-18 11:37 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        self._proxy_classifier._optimizer.step()  # type: ignore  # pylint: disable=W0212
Done.

2023-08-18 11:38 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +            perturbation = torch.reshape(perturbation, params_dict[name]["size"])  # type: ignore
The type checker expects second parameters to be tuple/list of integers and not a tensor. I have fixed it by changing the  size tensor to a list.

2023-08-18 11:38 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +
Added description

2023-08-18 11:38 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +
Fixed.

2023-08-18 11:39 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        params_dict = OrderedDict()  # type: ignore
Added type assignment to fix type checking error.

2023-08-18 11:39 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +    ) -> Tuple[Dict[str, Dict[str, "torch.Tensor"]], "torch.Tensor"]:  # pylint: enable=R0201
changed to static method.

2023-08-18 11:40 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +        for name, param in p_classifier._model.state_dict().items():  # pylint: disable=W0212
Done.

2023-08-18 11:40 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +
added description.

2023-08-18 11:40 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +
Done.

2023-08-18 11:41 UTC, Zaid-Hameed commented on art/defences/trainer/adversarial_trainer_awp_pytorch.py
> +            for name, param in p_classifier._model.named_parameters():  # pylint: disable=W0212
Done.

2023-08-18 11:41 UTC, Zaid-Hameed commented on examples/adversarial_training_awp.py
> +# Build a Keras image augmentation object and wrap it in ART
Changed to correct description.

2023-09-08 08:36 UTC, merged