Update `channels_first` parameter and docstring for PyTorch Object Detectors
Trusted-AI/adversarial-robustness-toolbox pull request #2265
Opened 2023-08-30 22:17 UTC by f4str

# Description

Set the `channels_first` parameter in `PyTorchObjectDetector` and `PyTorchFasterRCNN` to default to true instead of false and update the `input_shape` default parameter accordingly.

Additionally, update docstrings and the type hinting for `PyTorchFasterRCNN`.

Fixes #2264 

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test cases for `PyTorchObjectDetector` are unchanged
- [ ] Test cases for `PyTorchFasterRCNN` are unchanged
- [ ] Test cases for `PyTorchYolo` are unchanged

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-09-04 08:33 UTC, beat-buesser commented on art/estimators/object_detection/pytorch_faster_rcnn.py
> +        input_shape: Tuple[int, ...] = (3, 416, 416),
Does the Faster R-CNN model of torchvision expect this input size?

2023-09-04 08:34 UTC, beat-buesser requested changes
Hi @f4str Thank you very much for the pull request!  I have one question about the input shape, what do you think?

2023-09-05 19:43 UTC, f4str commented
Hi @beat-buesser thank you for the review. As per our discussion, it does make sense to leave the `input_shape` parameter for the `PyTorchObjectDetector` and `PyTorchFasterRCNN` as `(-1, -1, -1)` since they accept any input arbitrarily sized image. I've made the corresponding change.

2023-09-12 09:06 UTC, beat-buesser approved these changes

2023-09-12 09:06 UTC, merged