Added support for Composite Adversarial Attacks
Trusted-AI/adversarial-robustness-toolbox pull request #2287
Opened 2023-09-13 21:55 UTC by twweeb

# Description

This pull request add the support of the Composite Adversarial Attack (CSS) proposed in [1]. It provides an example notebook for explaining how to launch CAA.

[1] Towards Compositional Adversarial Robustness: Generalizing Adversarial Training to Composite Semantic Perturbations (CVPR 2023). [[Paper]](https://arxiv.org/abs/2202.04235), [[Demo]](https://hsiung.cc/CARBEN/), and [[Official repo]](https://github.com/IBM/composite-adv).

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [x] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [x] Unit Test
- [x] Notebook Example

**Test Configuration**:
- OS: Linux
- Python version: 3.8.18
- ART version or commit number: [818b50e99cbf659560d1a31a9b5283a94896e488](https://github.com/Trusted-AI/adversarial-robustness-toolbox/commit/818b50e99cbf659560d1a31a9b5283a94896e488)
- PyTorch version: 2.0.1+cu117
- Kornia version: 0.7.0

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-09-14 10:31 UTC, beat-buesser requested changes
Hi @twweeb Thank you very much for your pull request and contributing the Composite Adversarial Attack to ART! Your code looks good and I have added a few comments on the integration with ART. Please let me know what you think.

2023-09-14 20:24 UTC, twweeb commented on notebooks/composite-adversarial-attack.ipynb
> +{
Updated!

2023-09-14 20:24 UTC, twweeb commented on art/attacks/evasion/composite_adversarial_attack.py
> +# MIT License
Updated!

2023-10-27 11:57 UTC, beat-buesser requested changes
Hi @twweeb Thank you very much for the updates. I have added my final review and found only a few minor required changes.

2023-10-27 11:57 UTC, beat-buesser commented on tests/attacks/test_composite_adversarial_attack.py
> +    print("test_generate")
```suggestion
```

2023-10-27 11:57 UTC, beat-buesser commented on tests/attacks/test_composite_adversarial_attack.py
> +import torch
```suggestion
```

2023-10-27 11:57 UTC, beat-buesser commented on tests/attacks/test_composite_adversarial_attack.py
> +# MIT License
Please move this file to `tests/attacks/evasion/`.

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +    Note that this attack is intended for only PyTorch image classifiers with RGB images in the range [0, 1] as inputs.
I think we need the vertical line to guarantee a new line in the generated documentation.
```suggestion
    | Note that this attack is intended for only PyTorch image classifiers with RGB images in the range [0, 1] as inputs.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param data: A tensor of a batch of original inputs to be attacked.
We need an empty line for the automated documentation generation.
```suggestion
        Compute the adversarial examples for hue component.

        :param data: A tensor of a batch of original inputs to be attacked.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param data: A tensor of a batch of original inputs to be attacked.
We need an empty line for the automated documentation generation.
```suggestion
        Compute the adversarial examples for saturation component.

        :param data: A tensor of a batch of original inputs to be attacked.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param data: A tensor of a batch of original inputs to be attacked.
We need an empty line for the automated documentation generation.
```suggestion
        Compute the adversarial examples for rotation component.

        :param data: A tensor of a batch of original inputs to be attacked.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param data: A tensor of a batch of original inputs to be attacked.
We need an empty line for the automated documentation generation.
```suggestion
        Compute the adversarial examples for brightness component.

        :param data: A tensor of a batch of original inputs to be attacked.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param images: A tensor of a batch of original inputs to be attacked.
```suggestion
        The main algorithm to generate the adversarial examples for composite adversarial attack.

        :param images: A tensor of a batch of original inputs to be attacked.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param images: A tensor of a batch of original inputs to be attacked.
```suggestion
        Update the specified attack ordering.

        :param images: A tensor of a batch of original inputs to be attacked.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param data: A tensor of a batch of original inputs to be attacked.
```suggestion
        Compute the adversarial examples for L-infinity (PGD) component.

        :param data: A tensor of a batch of original inputs to be attacked.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param eta: The perturbation in the L-infinity ball.
```suggestion
        :param eta: The perturbation in the L-infinity ball.
        :param labels: A tensor of a batch of the original labels to be predicted.
```

2023-10-27 11:57 UTC, beat-buesser commented on art/attacks/evasion/composite_adversarial_attack.py
> +        :param data: A tensor of a batch of original inputs to be attacked.
```suggestion
        Compute the adversarial examples for contrast component.

        :param data: A tensor of a batch of original inputs to be attacked.
```

2023-10-28 03:30 UTC, twweeb commented
All comments are addressed.

2023-12-18 22:42 UTC, merged

2023-12-18 22:43 UTC, beat-buesser commented
Hi @twweeb Thank you very much for your first contribution to ART!