Added support for BEYOND [ICML-2024]
Trusted-AI/adversarial-robustness-toolbox pull request #2489
Opened 2024-09-03 08:45 UTC by allenhzy

# Description

This pull request adds the support of the BEYOND Detection method proposed in [1].

[1] Be Your Own Neighborhood: Detecting Adversarial Example by the Neighborhood Relations Built on Self-Supervised Learning. ICML. 2024[[Paper]](https://openreview.net/pdf?id=S4LqI6CcJ3)

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [x] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [x] Unit Test

**Test Configuration**:
- OS: Ubuntu 18.04
- Python version: 3.9.19
- ART version or commit number: 1.18.1
- Pytorch: 2.4.0
- cudnn version: 90100

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My changes have been tested using both CPU and GPU devices

2024-09-19 23:01 UTC, beat-buesser requested changes
Hi @allenhzy Thank you very much for your pull request! Could you please take a look at my review comments and add the proposed updates?

2024-12-05 15:38 UTC, allenhzy commented on art/defences/detector/evasion/beyond_detector.py
> +import abc
I've revised all codes that need to be revised

2024-12-05 15:38 UTC, allenhzy commented on tests/defences/detector/evasion/test_beyond_detector.py
> +        # Download pretrained weights from https://drive.google.com/drive/folders/1ieEdd7hOj2CIl1FQfu4-3RGZmEj-mesi?usp=sharing
> The pre-trained model has over 100 M

2024-12-09 11:28 UTC, beat-buesser reviewed
Hi @allenhzy Thank you very much for your updates! Could you please take a look above at my two last change requests and the alerts from CodeQL about unused variables?

2024-12-10 08:17 UTC, allenhzy commented on art/defences/detector/evasion/beyond_detector.py
> +logger = logging.getLogger(__name__)
I have revised the related codes.

2024-12-10 08:21 UTC, allenhzy commented
Dear Beat,

I have revised the codes.
Please check it.

Best,
Zhiyuan HE
发件人: Beat Buesser ***@***.***>
日期: 星期一, 2024年12月9日 下午7:29
收件人: Trusted-AI/adversarial-robustness-toolbox ***@***.***>
抄送: hzy ***@***.***>, Mention ***@***.***>
主题: Re: [Trusted-AI/adversarial-robustness-toolbox] Added support for BEYOND [ICML-2024] (PR #2489)

@beat-buesser commented on this pull request.

Hi @allenhzy<https://github.com/allenhzy> Thank you very much for your updates! Could you please take a look above at my two last change requests and the alerts from CodeQL about unused variables?

________________________________

In art/defences/detector/evasion/beyond_detector.py<https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/2489#discussion_r1875734678>:

> +"""

+This module implements the BEYOND detector for adversarial examples detection.

+| Paper link: https://openreview.net/pdf?id=S4LqI6CcJ3

+"""
⬇️ Suggested change

-"""

-This module implements the BEYOND detector for adversarial examples detection.

-| Paper link: https://openreview.net/pdf?id=S4LqI6CcJ3

-"""

+"""

+This module implements the BEYOND detector for adversarial examples detection.

+

+| Paper link: https://openreview.net/pdf?id=S4LqI6CcJ3

+"""

________________________________

In art/defences/detector/evasion/beyond_detector.py<https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/2489#discussion_r1875736394>:

> +# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE

+# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE

+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,

+# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE

+# SOFTWARE.

+"""

+This module implements the BEYOND detector for adversarial examples detection.

+| Paper link: https://openreview.net/pdf?id=S4LqI6CcJ3

+"""

+import numpy as np

+from typing import TYPE_CHECKING

+if TYPE_CHECKING:

+    from art.utils import CLASSIFIER_NEURALNETWORK_TYPE

+

+

+logger = logging.getLogger(__name__)

This line seems to cause the unittest errors because of the missing import of logging. Because the attack here is not actively using logging I suggest to remove this line.
⬇️ Suggested change

-logger = logging.getLogger(__name__)

—
Reply to this email directly, view it on GitHub<https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/2489#pullrequestreview-2488379055>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AF2RSJG555KPWYSJTCOORXT2EV5IFAVCNFSM6AAAAABNRUHJ7CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOBYGM3TSMBVGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-12-10 22:28 UTC, beat-buesser commented on art/defences/detector/evasion/beyond_detector.py
> +        augmentations: Optional[Callable] = None,
```suggestion
        augmentations: Callable | None,
```

2024-12-10 22:29 UTC, beat-buesser commented on art/defences/detector/evasion/beyond_detector.py
> +import numpy as np
```suggestion
from __future__ import annotations

import numpy as np
```

2024-12-10 22:29 UTC, beat-buesser commented on tests/defences/detector/evasion/test_beyond_detector.py
> +import logging
```suggestion
```

2024-12-12 15:03 UTC, beat-buesser commented
Hi @allenhzy I have merge this PR into the release branch, but I had to make some changes to remove errors that prevented the detector from running at all. Could you please take a look at the changes [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/commit/5ec99dc29dd501dda478fe39c5cfa3ffd7d87e9c) to see if they are correct and let me know?

2024-12-20 00:52 UTC, closed without merging