Change default return of PyTorchDeepSpeech.predict
Trusted-AI/adversarial-robustness-toolbox pull request #689
Opened 2020-10-27 20:00 UTC by beat-buesser

Signed-off-by: Beat Buesser <beat.buesser@ie.ibm.com>

# Description

This pull request changes the default return format of method `predict` in `PyTorchDeepSpeech` from a Tuple of probabilities and sequence lengths to an array of transcriptions (array of predicted strings). This change aligns `PyTorchDeepSpeech` with the other ART estimators to predict by default in the same format as it accepts as input. This change also enables using `PyTorchDeepSpeech` with `ProjectedGradientDescent` and `FastGradientMethod` in cases where no labels are provided to their method `generate` and these attacks use the labels predicted by `PyTorchDeepSpeech` 's method `predict`.

Fixes #688

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [x] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-10-27 22:24 UTC, davidslater requested changes
This change works fine, but does not completely resolve issue #688.

If the input batch is not an object type, such as:
```
(Pdb) x
array([[ 0.0000000e+00, -3.0517578e-05,  3.0517578e-05, ...,
        -1.2207031e-04, -1.2207031e-04, -9.1552734e-05]], dtype=float32)
(Pdb) x.shape, x.dtype
((1, 238400), dtype('float32'))
```

The estimator has no trouble running predict and loss_gradient. However, loss_gradient will always return an object type:
```
(Pdb) grad = estimator.loss_gradient(x)
(Pdb) grad
array([array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)], dtype=object)
```
This will cause FGSM to fail here:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/dev_1.4.2/art/attacks/evasion/fast_gradient.py#L302-L307
In particular, `batch` will be of type float32 but `grad` will be of type object. Then it will return the else branch and return this error:
```
*** ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
when it hits this line:
```
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/dev_1.4.2/art/attacks/evasion/fast_gradient.py#L287
```

Instead of modifying FGSM and the other attacks, I recommend forcing the estimator to make the gradient dtype match the input to loss_gradient. This could be done by adding the following lines to the end of `loss_gradient` right before `return results`:
```
if x.dtype != np.object:
    results = np.array([i for i in results], x.dtype)
    assert results.shape == x.shape and results.dtype == x.dtype  # if you want to check
```

2020-10-27 22:28 UTC, davidslater commented
To add a little more, if the input array is already an object, the attack works fine.
```
(Pdb) x
array([[ 0.0000000e+00, -3.0517578e-05,  3.0517578e-05, ...,
        -1.2207031e-04, -1.2207031e-04, -9.1552734e-05]], dtype=float32)
(Pdb) attack.generate(x)
2020-10-27 22:09:34 cf9335aafa47 art.attacks.evasion.fast_gradient[4440] INFO Using model predictions as correct labels for FGM.
*** ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
(Pdb) x_ = np.array([x_i for x_i in x] + [np.array([0.1]), np.array([0.1, 0.2])])[:-2]
/workspace/armory/scenarios/audio_asr.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """
(Pdb) x_.shape
(1,)
(Pdb) x_.dtype
dtype('O')
(Pdb) attack.generate(x_)
2020-10-27 22:25:54 cf9335aafa47 art.attacks.evasion.fast_gradient[4440] INFO Using model predictions as correct labels for FGM.
array([array([-0.2       ,  0.19996949,  0.20003052, ..., -0.20012207,
        0.19987793, -0.20009156], dtype=float32)], dtype=object)
```

2020-10-28 00:15 UTC, beat-buesser commented
@davidslater Thank you very much for identifying this case! It looks like it occurs only for non-np.object arrays of a single sample and we tested with two samples. I was able to reproduce your solution and have commited it above.

2020-10-28 15:00 UTC, davidslater approved these changes
LGTM

2020-10-28 16:07 UTC, merged