Add Carlini and Wagner audio attack on ASR systems
Trusted-AI/adversarial-robustness-toolbox pull request #784
Opened 2020-12-04 17:56 UTC by hesseltuinhof

# Description

This PR adds the `CarliniWagnerASR` attack module. It is implemented as a special case of the `ImperceptibleASR`, where `max_iter_stage_2` is zero by default. Thus skipping the second stage of that attack.

Furthermore, the PR includes some commits from #760 that were not correctly applied during the 1.5 release. 

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [x] New feature (non-breaking)

# Testing

Several tests have been added to the test suite.

**Test Configuration**:
- Fedora 33
- Python 3.8.6
- ART 1.5.1 development

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-12-07 20:46 UTC, beat-buesser commented on art/attacks/evasion/adversarial_asr.py
> +        self.masker = None
We need to update the typing of self.masker to include `None`.

2020-12-07 20:47 UTC, beat-buesser commented on art/attacks/evasion/adversarial_asr.py
> +        EvasionAttack.__init__(self, estimator=estimator)
Can we disable Pylint warnings for W0233 and W0231 in this line?

2020-12-07 20:55 UTC, beat-buesser requested changes
Hi Hessel, I have two minor comments above, what do you think?

2020-12-09 15:59 UTC, hesseltuinhof commented
I fully agree with your two comments and I have rebased the PR accordingly :100:

2020-12-09 21:04 UTC, beat-buesser approved these changes
@hesseltuinhof Thank you very much!

2020-12-09 21:04 UTC, merged