Add missing params to estimator_params in sub-classes
Trusted-AI/adversarial-robustness-toolbox pull request #857
Opened 2021-01-20 07:16 UTC by abigailgold

# Description

All sub-classes of BaseEstimator should add to the estimator_params field their specific parameters.

Fixes # (821)

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ X] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

Unit tests for changed classes.

**Test Configuration**:
- OS: MacOS 10.15.7
- Python version 3.7
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [X ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes

2021-01-26 15:06 UTC, beat-buesser commented on art/estimators/object_detection/tensorflow_faster_rcnn.py
> +
Can we remove these line?

2021-01-26 15:56 UTC, abigailgold commented on art/estimators/object_detection/tensorflow_faster_rcnn.py
> +
Yes, of course. I will push a fix.

2021-01-26 21:02 UTC, beat-buesser requested changes
Hi @abigailgold Thank you very much for the pull request!

It looks like in classes inheriting from multiple base classes only one base class is used to update `estimator_params`. Would it be possible to include the arguments of all base classes, including the mixins, in `estimator_params`?

Should we update the codes and replace the calls to `self._variable` with calls to the corresponding new property `self.variable`?

2021-01-27 09:44 UTC, abigailgold commented
Hi @beat-buesser in most mixin classes I did not see any params, and if there were I just included them directly in the sub-class params (such as in the case of channels_first in NeuralNetworkMixin). If you prefer I can move that into the mixin class and have all sub-classes do: estimator_params = PyTorchEstimator.estimator_params + NeuralNetworkMixin.estimator_params + ...). Is this what you meant?

Regarding the calls to self._variable, I think both options are ok, so whatever you think is best.

2021-01-28 22:44 UTC, beat-buesser commented
@abigailgold Great, I didn't notice. I think `estimator_params = PyTorchEstimator.estimator_params + NeuralNetworkMixin.estimator_params ` would be more explicit about the addition. About `self._variable`, I think we can leave it as is for now.

2021-02-02 23:16 UTC, beat-buesser approved these changes

2021-02-02 23:16 UTC, merged