Expand range of eps_step and eps in PGD attacks
Trusted-AI/adversarial-robustness-toolbox pull request #882
Opened 2021-02-03 14:36 UTC by beat-buesser

Signed-off-by: Beat Buesser <beat.buesser@ie.ibm.com>

# Description

This pull request adds support for `eps_step` larger than `eps` for all norms, `eps_step = np.inf` to enable stepping immediately towards the boundary of clip values in the direction of the gradient, and `eps=0` to zero any perturbation for debugging purposes.

Fixes #823

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-03 14:38 UTC, beat-buesser commented
Hi @davidslater I think this should solve #823. What do you think, especially about the implementation of `eps_step = np.inf`?

2021-03-11 18:03 UTC, davidslater requested changes
I think it generally looks good, but had some questions of how you're avoiding NaNs when eps_step is a vector.

2021-03-11 18:03 UTC, davidslater commented on art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
> +                )
Ditto on my comments above

2021-03-11 18:03 UTC, davidslater commented on art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
> +                x = tf.clip_by_value(x, clip_min, clip_max)
Ditto on my comments above

2021-03-11 19:32 UTC, beat-buesser commented on art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
>                  raise ValueError("The perturbation size `eps` has to be positive.")
Ok.

2021-03-11 19:33 UTC, beat-buesser commented on art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py
>                  raise ValueError("The perturbation size `eps` has to be positive.")
Ok.

2021-03-11 19:34 UTC, beat-buesser commented on art/attacks/evasion/fast_gradient.py
>                  raise ValueError("The perturbation size `eps` has to be positive.")
Ok.

2021-03-11 19:34 UTC, beat-buesser commented on art/attacks/evasion/fast_gradient.py
>                  raise ValueError("The perturbation size `eps` has to be positive.")
Ok.

2021-03-11 20:22 UTC, beat-buesser commented on art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_numpy.py
Yes, that makes sense.

2021-03-11 20:38 UTC, beat-buesser commented on art/attacks/evasion/fast_gradient.py
> +                batch = np.clip(batch, clip_min, clip_max)
No, actually I think this looks much better.

2021-03-11 20:44 UTC, beat-buesser commented on art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py
> +                )
Ok.

2021-03-11 21:00 UTC, beat-buesser commented on art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_tensorflow_v2.py
> +                x = tf.clip_by_value(x, clip_min, clip_max)
Ok.

2021-03-12 17:48 UTC, davidslater approved these changes
LGTM

2021-03-12 23:59 UTC, merged