Improve Psychoacoustic model and some ASR maintenance
Trusted-AI/adversarial-robustness-toolbox pull request #930
Opened 2021-03-03 16:02 UTC by hesseltuinhof

# Description

This PR fixes the Psychoacoustic model and stabilizes the imperceptible loss. Especially, switching to `librosa`'s STFT and using scalar PSD maximum, fixes stability issues with the imperceptible loss.

Fixes #929

Furthermore, the PR includes several minor improvements to ensure that framework-agnostic imperceptible ASR works as expected. These include:

* Return transcription as default in predict as explained in docstring  (Deepspeech estimator)
* Fix wrong gradient shape if `batch_size=1` as explained in docstring (Deepspeech estimator)
* Use periodic window for STFT instead symmetric window (Deepspeech-specific attack)
* Ensure correct `dtype` and streamline formulas to increase numerical stability (Psychoacoustic models)
* Refactor loss theta to only calculate masking thresholds once (Framework-agnostic attack)
* Add early stopping if loss theta < 0.05 to avoid running into gradients with `nan` values (Framework-agnostic attack)

## Type of change

Please check all relevant options.

- [x] Improvement (non-breaking)
- [x] Bug fix (non-breaking)

# Testing

Changes have been tested against the ten LibriSpeech test samples provided by Qin et al.

**Test Configuration**:
- Fedora 33
- Python 3.6.10
- ART 1.5.3 development

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-03 16:18 UTC, beat-buesser commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        **kwargs,
Why do you add `kwargs`? Can we add the argument `loss_theta_min` instead?

2021-03-03 16:21 UTC, beat-buesser commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +    def _stabilized_threshold_and_psd_maximum(self, x: np.ndarray):
What is the type of the returned value?

2021-03-03 16:22 UTC, beat-buesser commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +            #   masking threshold formula will always return a value different to np.inf
```suggestion
            # masking threshold formula will always return a value different to np.inf
```

2021-03-03 16:24 UTC, beat-buesser commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        import librosa
Should we add `librosa` to `requirements.txt`?

2021-03-03 16:25 UTC, beat-buesser commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +    def _stabilized_threshold_and_psd_maximum(self, x: np.ndarray):
Please add in the docstring a description of argument `x`.

2021-03-03 16:26 UTC, beat-buesser requested changes
Hi @hesseltuinhof Looks good to me! I have only a few minor update requests.

2021-03-09 12:22 UTC, beat-buesser commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        self._loss_theta_min = loss_theta_min
```suggestion
        self.loss_theta_min = loss_theta_min
```

2021-03-09 12:25 UTC, beat-buesser commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +                        "Batch sample %s reached minimum threshold of %s for theta loss.", j, self._loss_theta_min
```suggestion
                if loss_theta[j] < self.loss_theta_min and not early_stop[j]:
                    logger.warning(
                        "Batch sample %s reached minimum threshold of %s for theta loss.", j, self.loss_theta_min
```

2021-03-09 12:25 UTC, beat-buesser commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        """Return batch of stabilized masking thresholds and PSD maxima.
```suggestion
        """
        Return batch of stabilized masking thresholds and PSD maxima.
```

2021-03-09 14:19 UTC, minhitbk commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
>          self._targeted = True
```suggestion
        self.targeted = True
```

2021-03-09 14:33 UTC, minhitbk commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        dtype = np.float32 if x.ndim != 1 else np.object
```suggestion
        dtype = ART_NUMPY_DTYPE if x.ndim != 1 else np.object
```

2021-03-09 14:34 UTC, minhitbk commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        dtype = np.float32 if x.ndim != 1 else np.object
```suggestion
        dtype = ART_NUMPY_DTYPE if x.ndim != 1 else np.object
```

2021-03-09 14:35 UTC, minhitbk commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        dtype = np.float32 if x.ndim != 1 else np.object
```suggestion
        dtype = ART_NUMPY_DTYPE if x.ndim != 1 else np.object
```

2021-03-09 14:35 UTC, minhitbk commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        alpha = np.array([self.alpha] * batch_size, dtype=np.float32)
```suggestion
        alpha = np.array([self.alpha] * batch_size, dtype=ART_NUMPY_DTYPE)
```

2021-03-09 14:38 UTC, minhitbk commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        dtype = np.float32 if x.ndim != 1 else np.object
```suggestion
        dtype = ART_NUMPY_DTYPE if x.ndim != 1 else np.object
```

2021-03-09 14:41 UTC, minhitbk commented on art/attacks/evasion/imperceptible_asr/imperceptible_asr.py
> +        audio_float = audio.astype(np.float32)
```suggestion
        audio_float = audio.astype(ART_NUMPY_DTYPE)
```

2021-03-09 14:43 UTC, minhitbk commented on art/estimators/speech_recognition/tensorflow_lingvo.py
> +        dtype = np.float32 if x.ndim != 1 else np.object
```suggestion
        dtype = ART_NUMPY_DTYPE if x.ndim != 1 else np.object
```

2021-03-09 14:44 UTC, minhitbk commented on art/estimators/speech_recognition/tensorflow_lingvo.py
> +        dtype = np.float32 if x.ndim != 1 else np.object
```suggestion
        dtype = ART_NUMPY_DTYPE if x.ndim != 1 else np.object
```

2021-03-09 14:47 UTC, minhitbk approved these changes
Hi @hesseltuinhof : I have just a few minor comments. One of that is that I suggest to import ART_NUMPY_DTYPE and use it to replace any `np.float32` in your code. Similarly, you can define one for tf.float32. I remember torch.float32 is also defined somewhere which we can confirm with @beat-buesser.

2021-03-10 12:46 UTC, hesseltuinhof commented
Thanks for the reviews. All issues have been addressed. The choice for using `np.float32` is deliberate as discussed.

2021-03-10 19:11 UTC, beat-buesser approved these changes

2021-03-10 19:13 UTC, beat-buesser commented
Hi @hesseltuinhof Thank you very much! These updates make the Imperceptible ASR attack even stronger!

2021-03-10 19:13 UTC, merged