Fix bug in elastic net attack
Trusted-AI/adversarial-robustness-toolbox pull request #995
Opened 2021-03-25 16:19 UTC by minhitbk

# Description
Fix bug in elastic net attack.
Fixes #966 

## Type of change

Please check all relevant options.

- [ ] Improvement (non-breaking)
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing

Please describe the tests that you ran to verify your changes. Consider listing any relevant details of your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
- OS
- Python version
- ART version or commit number
- TensorFlow / Keras / PyTorch / MXNet version

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-31 20:54 UTC, beat-buesser commented on art/attacks/evasion/elastic_net.py
> +
```suggestion
```

2021-03-31 20:55 UTC, beat-buesser commented on art/attacks/evasion/elastic_net.py
> +        loss_gradient[cond] = 0.0
```suggestion
        # Set gradients where loss is constant to zero
        cond = (predictions[i_add] - predictions[i_sub] + self.confidence) < 0
        loss_gradient[cond] = 0.0
```

2021-03-31 20:55 UTC, beat-buesser commented on art/attacks/evasion/elastic_net.py
> +            cond = (z_target - z_other + self.confidence) < 0
```suggestion
```

2021-03-31 20:56 UTC, beat-buesser commented on art/attacks/evasion/elastic_net.py
> +
```suggestion
```

2021-03-31 20:57 UTC, beat-buesser requested changes
Hi @minhitbk Thank you very much for fixing this bug. I have a proposal to reuse the `i_add` and `i_sub` variables. What do you think, would this work?

2021-04-01 10:38 UTC, minhitbk commented
> Hi @minhitbk Thank you very much for fixing this bug. I have a proposal to reuse the `i_add` and `i_sub` variables. What do you think, would this work?

Hi @beat-buesser : I don't think it works when you extract  predictions[i_sub] and predictions[i_add] as batch.

2021-04-06 22:56 UTC, beat-buesser approved these changes

2021-04-06 22:57 UTC, beat-buesser commented
@minhitbk Thank you!

2021-04-06 22:57 UTC, merged